### ISSUE TITLE
Some bad defaults in the suggested configuration?

### ISSUE THREAD

**Issue by InverseFalcon** [graphaware/neo4j-expire#14]
In the readme for the configuration properties to apply to neo4j.conf, we can see:

```
#By default, all created/updated nodes and relationships are checked for the presence of expire/ttl property.
#As with most GraphAware Modules, nodes and relationships this module applies to can be limited by the use of SPeL, e.g.:
com.graphaware.module.EM.node=hasLabel('NodeThatExpiresAtSomePoint')
com.graphaware.module.EM.relationship=isType('TEMPORARY_RELATIONSHIP')
```

Doesn't the presence of these uncommented lines means that it will only be looking at `:NodeThatExpiresAtSomePoint` nodes and `:TEMPORARY_RELATIONSHIP` types instead of all updated nodes and relationships? Seems like these should be commented out to adhere with the note about default behavior.

**Comment by luanne** [comment]
I suppose that is one way of looking at it. The above is in line with all our module configurations documentation- more as a description and example rather than the entire default configuration to be copied into neo4j.conf
Thanks for raising this, we will keep it in mind when we revisit our documentation
